CREATE TABLE TELEBOT_APP.TELEBOT_USER
(
    id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    date_created  DATE DEFAULT SYSDATE NOT NULL,
    date_updated  DATE DEFAULT SYSDATE,
    chat_id       NUMBER               NOT NULL,
    user_id       NUMBER               NOT NULL,
    user_name     NVARCHAR2(36),
    user_name_ext NVARCHAR2(200)       NOT NULL,

    CONSTRAINT telebot_user_pk PRIMARY KEY (id)
);

CREATE TABLE TELEBOT_APP.TELEBOT_MESSAGE
(
    id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    severity      NVARCHAR2(20)        NOT NULL, -- INFO, WARNING, ERROR, FATAL, PANIC
    system        NVARCHAR2(100)       NOT NULL, -- System that sent a message
    service       NVARCHAR2(100)       NOT NULL, -- Service affected
    content       NVARCHAR2(2000)      NOT NULL,
    date_received DATE DEFAULT SYSDATE NOT NULL,
    date_sent     DATE,

    CONSTRAINT telebot_message_pk PRIMARY KEY (id)
);

CREATE TABLE TELEBOT_APP.TELEBOT_GROUP
(
    id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    group_code   NVARCHAR2(30)        NOT NULL,
    description  NVARCHAR2(200),
    date_updated DATE DEFAULT SYSDATE NOT NULL,

    CONSTRAINT telebot_group_pk PRIMARY KEY (id)
);

INSERT INTO TELEBOT_APP.TELEBOT_GROUP (group_code, description)
VALUES ('ADMINS', 'Admin users');
INSERT INTO TELEBOT_APP.TELEBOT_GROUP (group_code, description)
VALUES ('ALL', 'Registered users receiving FATAL and PANIC' ||
               ' messages');
INSERT INTO TELEBOT_APP.TELEBOT_GROUP (group_code, description)
VALUES ('TECH_STAFF', 'Receives all the messages except ' ||
                      'INFO');
INSERT INTO TELEBOT_APP.TELEBOT_GROUP (group_code, description)
VALUES ('DEBUGGERS', 'Receives ALL the messages');

CREATE TABLE TELEBOT_APP.TELEBOT_LNK_USER_GROUP
(
    id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    user_id      NUMBER               NOT NULL,
    group_id     NUMBER               NOT NULL,
    date_updated DATE DEFAULT SYSDATE NOT NULL,
    active       NUMBER(1),

    CONSTRAINT telebot_lnk_user_group_pk PRIMARY KEY (id)
);